### ISSUE TITLE
Update RFC XML V3 processor to follow new schema

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#11]
Apparently the V3 schema has changed so much that our generated v3 XML is raising tons of warnings when read by `xml2rfc`.

This issue is to align our generated XML with the latest RFC XML V3 schema.

**Comment by opoudjis** [comment]
... This will have been overtaken by events anyway, since the whole gem is going to change.

**Comment by opoudjis** [comment]
Obsoleted by #47, second phase (Levkowwtz draft)
