### ISSUE TITLE
Structure of bibliography: normative vs informative references

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#113]
This input:

```adoc
== References

[bibliography]
=== Normative References

[bibliography]
=== Informative References
```

Will cause both `<middle>` and `<back>` to both have duplicated `references` sections which kills the XML RFC output. This is a metanorma-ietf bug.

```xml
<middle>
  ...
  <section anchor="_references">
    <name>References</name>
    <div>
      <name>Normative references</name>
      <reference target="https://www.rfc-editor.org/info/rfc5322" anchor="RFC5322">
        <front>
          <title>Internet Message Format</title>
      ...
      </reference>
    ...
    <div>
      <name>Bibliography</name>
      <reference target="https://www.rfc-editor.org/info/rfc5598" anchor="RFC5598">
      ...
  </section>
</middle>
<back>
  <references anchor="_normative_references">
    <name>Normative references</name>
    <reference target="https://www.rfc-editor.org/info/rfc5322" anchor="RFC5322">
  ...
  <references anchor="_informative_references">
    <name>Bibliography</name>
    <reference target="https://www.rfc-editor.org/info/rfc5598" anchor="RFC5598">
  ...
</back>
----

The relevant errors are:
```
Metanorma XML Syntax: (XML Line 000150:93): attribute "inline-header" not allowed here; expected attribute "language", "numbered", "removeInRFC", "script" or "toc"
Metanorma XML Syntax: (XML Line 000150:93): attribute "obligation" not allowed here; expected attribute "language", "numbered", "removeInRFC", "script" or "toc"
Metanorma XML Syntax: (XML Line 000158:148): attribute "inline-header" not allowed here; expected attribute "language", "numbered", "removeInRFC", "script" or "toc"
Metanorma XML Syntax: (XML Line 000158:148): attribute "obligation" not allowed here; expected attribute "language", "numbered", "removeInRFC", "script" or "toc"
Metanorma XML Syntax: (XML Line 000179:93): attribute "obligation" not allowed here; expected attribute "language", "numbered", "removeInRFC", "script" or "toc"
Metanorma XML Syntax: (XML Line 000804:95): attribute "inline-header" not allowed here; expected attribute "language", "numbered", "obligation", "removeInRFC", "script" or "toc"
```

The correct output is:

```xml
<middle>
  ...
</middle>
<back>
  <references anchor="_normative_references">
    <name>Normative references</name>
    <reference target="https://www.rfc-editor.org/info/rfc5322" anchor="RFC5322">
  ...
  <references anchor="_informative_references">
    <name>Bibliography</name>
    <reference target="https://www.rfc-editor.org/info/rfc5598" anchor="RFC5598">
  ...
</back>
```

This can be generated with this input, but Metanorma-IETF should always generate the correct output:
```adoc
[bibliography]
== Normative References

[bibliography]
== Informative References
```

**Comment by opoudjis** [comment]
Hierarchical arrangement of `<clause><references>` needs to be preserved in RFC XML as `references/references`
