### ISSUE TITLE
Terms and definitions section ignores "notation conventions" as required by RFC 8174

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#119]
In RFCs this particular paragraph is required:

> The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*NOT RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in BCP 14 of <<RFC2119>> and <<RFC8174>> when, and only when, they appear in all capitals, as shown here.

However, the current terms and definitions clause does not allow it:

```adoc
[[terms]]
== Terms and Definitions

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*NOT RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in BCP 14 of <<RFC2119>> and <<RFC8174>> when, and only when, they appear in all capitals, as shown here.

=== Prompt

JSON sent from the server to the client describing the tests the client performs
```

Will end up as:

<img width="555" alt="Screen Shot 2020-12-08 at 12 08 06 PM" src="https://user-images.githubusercontent.com/11865/101438760-093a9a80-394e-11eb-8289-0a81bb005c52.png">

It is clear to me that the required paragraph can be fit into the semantic meaning of "terms and definitions". Unless we're advising people to put this paragraph elsewhere.

**Comment by opoudjis** [comment]
Will be implemented as a "boilerplate" subclause in terms and definitions, which will result in it not getting a subclause header.

**Comment by opoudjis** [comment]
So the markup here needs to become:

````
[[terms]]
== Terms and Definitions

[.boilerplate]
=== {blank}
The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*NOT RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in BCP 14 of <<RFC2119>> and <<RFC8174>> when, and only when, they appear in all capitals, as shown here.

=== Prompt

JSON sent from the server to the client describing the tests the client performs
````

**Comment by ronaldtse** [comment]
Can't we do this?

```
[[terms]]
== Terms and Definitions

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*NOT RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in BCP 14 of <<RFC2119>> and <<RFC8174>> when, and only when, they appear in all capitals, as shown here.

=== Prompt

JSON sent from the server to the client describing the tests the client performs
```

**Comment by opoudjis** [comment]
Revising solution, and reversing existing Metanorma behaviour:

* A boilerplate clause replaces existing boilerplate
* Random text at the start of a document is not stripped: it is appended to existing boilerplate.
