### ISSUE TITLE
Cannot generate standard refererence sections

### ISSUE THREAD

**Issue by petithug** [metanorma/metanorma-ietf#128]
A standard reference section has the following shape:

```
   10. References  . . . . . . . . . . . . . . . . . . . . . . . . .  17
     10.1.  Normative References . . . . . . . . . . . . . . . . . .  17
     10.2.  Informative References . . . . . . . . . . . . . . . . .  17
```

The issue is that I cannot find a way to generate the equivalent xml2rfc v3 source.

The following does not work (the second section is displayed as "Bibliography".  Also the first one is modified as "Normative references", with a lowercase.  But anyway the "References" section would be missing):

```
[bibliography]
== Normative References

[bibliography]
== Normative References
```

The following does not work either:

```
== References

[bibliography]
=== Normative References

[bibliography]
=== Normative References
```

**Comment by ronaldtse** [comment]
I suspect you meant:

```adoc
[bibliography]
== Normative References

[bibliography]
== Informative References
```

Or 

```adoc
== References

[bibliography]
=== Normative References

[bibliography]
=== Informative References
```

Looks like a bug to me. @opoudjis do you have time to verify? Thanks.

**Comment by opoudjis** [comment]
Confirmed that "Normative References" is being overwritten with "Bibliography". 

There is code to process `<references>` recursively, which means that 

````
== References

[bibliography]
=== Normative References

[bibliography]
=== Informative References
````

should be working. It is not, and I will need to work out why.

**Comment by opoudjis** [comment]
Suppressed normalisation of bibliography names.

**Comment by opoudjis** [comment]
References generated correctly with the foregoing markup:

````
 1.  Clause  . . . . . . . . . . . . . . . . . . . . . . . . . . .   2
   2.  References  . . . . . . . . . . . . . . . . . . . . . . . . .   2
     2.1.  Normative References  . . . . . . . . . . . . . . . . . .   2
     2.2.  Informative References  . . . . . . . . . . . . . . . . .   2
   Author's Address  . . . . . . . . . . . . . . . . . . . . . . . .   2
````

**Comment by petithug** [comment]
I confirm that this is fixed.
