### ISSUE TITLE
Unable to set author in XML RFC v3

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#138]
From @douglm

> I'm able to generate something that runs through xm2rfc however I noticed the address isn't getting filled in. I have this:

```
:fullname: Michael Douglass
:lastname: Douglass
:forename_initials: M.
:organization: Spherical Cow Group
:street: 226 3rd Street
:city: Troy
:state: NY
:code: 12180
:country: United States of America
:uri: https://sphericalcowgroup.com/
:email: mikeadouglass@gmail.com
```

> but this is what ends up in the xml:

```
<author fullname="Michael Douglass">
  <address>
    <postal></postal>
    <email>mikeadouglass@gmail.com</email>
    <uri></uri>
  </address>
</author>
```

**Comment by ronaldtse** [comment]
@CAMOBAP can we verify this? Thanks!

**Comment by ronaldtse** [comment]
I have verified that this is a real bug. This occurs in mn-samples-ietf as well:

```adoc
:organization: BBN STC
:phone: (617) 873-4323
:contributor-uri: http://bbn.com
:consensus: true
:street: 10 Moulton Street
:city: Cambridge
:code: MA 02238
:organization_2: BBN STC
:phone_2: (617) 873-4323
:street_2: 10 Moulton Street
:city_2: Cambridge
:code_2: MA 02238
:contributor-uri_2: http://opoudjis.net
:equivalent: http://example1.com
:derived-from: RFC 1149
:surname: Waitzman
:givenname: David
:email: dwaitzman@BBN.COM
:surname_2: Nicholas
:givenname_2: Nick
:email_2: opoudjis@gmail.com
```

=>

```xml
    <author initials="D" surname="Waitzman">
      <address>
        <postal></postal>
        <phone>(617) 873-4323</phone>
        <email>dwaitzman@BBN.COM</email>
        <uri>http://bbn.com</uri>
      </address>
    </author>
    <author initials="N" surname="Nicholas">
      <address>
        <postal></postal>
        <phone>(617) 873-4323</phone>
        <email>opoudjis@gmail.com</email>
        <uri>http://opoudjis.net</uri>
      </address>
    </author>
```

**Comment by opoudjis** [comment]
Please refer to https://www.metanorma.org/author/ietf/ref/document-attributes/#author-attributes

`:organization:` should be `:affiliation`.

`:uri:` should be `:contributor-uri:`. `:uri:` is the document URL.

As noted on the page:

> `:address:`: Used to directly format postal addresses without regard to the prior types. Multiple lines are given as separate lines, each ending with plus and backslash (" + \"). The postal-line attribute is mutually exclusive with the presence of street, city, region, country and code attributes (which are not currently supported). RFC XML: front/author/address/postal/postalLine

(We did not implement address breakdowns because they do not fit our high level address model currently in Metanorma. Yes, I can implement them, but not quickly.)

So the address needs to be given as:

````
:fullname: Michael Douglass
:lastname: Douglass
:forename_initials: M.
:affiliation: Spherical Cow Group
:address: 226 3rd Street +\
Troy NY 12180 +\
United States of America
:contibutor-uri: https://sphericalcowgroup.com/
:email: mikeadouglass@gmail.com
````

**Comment by douglm** [comment]
The example docs probably need changing - pretty sure I compared with those

**Comment by opoudjis** [comment]
@ronaldtse has updated the example docs.

https://github.com/metanorma/metanorma-ietf/issues/140 to add address breakdown attributes back in.
