### ISSUE TITLE
Support RFC XML v3 street, city, region, country and code elements

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#140]
From metanorma.org:

> The `postal-line` attribute is mutually exclusive with the presence of `street`,
> `city`, `region`, `country` and `code` attributes (which are not currently supported).

We used to support these attributes in Metanorma-IETF v2, but they were removed in v3 in favour of the new `postal-line` RFC XML element. 

For backwards compatibility, we should support these old attributes, too.

**Comment by opoudjis** [comment]
It turns out that these were never removed from biblio.rnc, where they are supported as: `(street+, city, state?, country, postcode) | formattedAddress`. So will support these generically in standoc

**Comment by opoudjis** [comment]
And we need fallback formatted rendering of these in isodoc:

````
street
state
city
country postcode
````
