### ISSUE TITLE
Should we fail on missing xml2rfc?

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-ietf#143]
Currently, we just print error but return 0 exit code
```
[metanorma-ietf] Error: unable to generate txt, the command `xml2rfc` is not found in path.
[metanorma-ietf] Error: unable to generate html, the command `xml2rfc` is not found in path.
```

Full log: https://github.com/metanorma/packed-mn/runs/2457705761?check_suite_focus=true#step:5:90

@ronaldtse @opoudjis how do you think?

**Comment by ronaldtse** [comment]
We should definitely return errored code.

**Comment by CAMOBAP** [comment]
PRs ready for review:
 - #144 
 - metanorma/metanorma#186
 - metanorma/mn2pdf-ruby#18
