### ISSUE TITLE
Convert Metanorma XML to RFC XML

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma-ietf#15]
Hi, this just placeholder to keep a reference of what needs to be done on this process

**Comment by abunashir** [comment]
Hi @ronaldtse, @opoudjis: Can you refer me to a complete example of an IETF document (in asciidoc) that I can use as a reference point to make sure this conversion process covers it all?

**Comment by abunashir** [comment]
@ronaldtse: Any thoughts on this one?

**Comment by ronaldtse** [comment]
@abunashir there are many examples in our GitHub account. These are some RFCs submitted to the IETF datatracker:

* Minimal example: https://github.com/riboseinc/rfc-asciirfc-minimal
* Very long example: https://github.com/riboseinc/rfc-asciidoc-rfc
* https://github.com/riboseinc/rfc-divination-cfapi
* https://github.com/riboseinc/rfc-camelot-holy-grenade

We just need to ensure the generated RFC XML v2 / v3 copy using the old gem and the new gem are the same. Thanks!

**Comment by abunashir** [comment]
Cool, thanks @ronaldtse! I will start working on it next
