### ISSUE TITLE
Disable on-demand IETF WG/Area fetching and validation

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#156]
The answer on IETF WG/Area validation is provided here:
https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/27

1. There is no authoritative list
2. There is no guidance on the correct format
3. We should provide this information inside metanorma-ietf (and potentially updated by the mirrored metanorma-ietf-data) because we cannot expect tools.ietf.org be always up. 

We should only issue warnings but not failures for values. 

From @opoudjis:

> The only thing I can suggest here is disabling validation against the IETF workgroups, by disabling validation completely, by inserting `:novalid:` as a document attribute. That isn't appropriate in general in mn-samples-ietf, since we do want to test for the validity of validation in those samples; but I think it is appropriate for a standalone repository like this.

> But yes, this is the only cache file retrieved specific to the IETF flavour; although the document does also retrieve bibliographic references via relaton, like any another document.

_Originally posted by @opoudjis in https://github.com/metanorma/rfc-camelot-holy-grenade/issues/13#issuecomment-873067388_

**Comment by CAMOBAP** [comment]
PR is ready for review
