### ISSUE TITLE
The revdate document attribute is not used to generate the date

### ISSUE THREAD

**Issue by petithug** [metanorma/metanorma-ietf#157]
Apparently published-date and circulated-date are used instead of rev-date in the code, but that contradicts the documentation.

**Comment by opoudjis** [comment]
That may well be legacy in documentation: metanorma does indeed privilege published-date, and revdate is only intended now for minor versions

**Comment by ronaldtse** [comment]
Thanks @petithug looks like a bug in the documentation. We previously indeed use `revdate` for the versioning but it is now superseded by the new "generic bibliographic dates". We shall get the docs updated.
