### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ietf#161]
From @petithug :

As discussed, please find below a first batch of issues found in metanorma-ietf and/or its documentation.  For this batch I focused on the AsciiDoc marks that can be used inline.  But first a few words about my methodology.  My goal is in two parts:

First be sure that there is a way from a metanorma-ietf document to generate *all* valid RFC7991+ elements, without exceptions.  By RFC7991+ I mean the xml2rfc v3 schema (https://github.com/rfc-format/v3grammar/blob/master/v3.rnc-3.0.0) used in the latest version of the xml2rfc program.  This what the RFC Editor actually uses, because this is what the xml2rfc program uses.  Complete support is needed so users do not have an excuse to switch to another format.

Second, I want to be sure that the documentation reflects that.  If it does not, then again users will abandon that format and go back to kramdown-rfc2629.

The way I am testing these two things is by designing an Idris module usable in a computerate document that can generate a metanorma-ietf document that can then be used to generate a valid xml2rfc (notice that I do not care about generating txt or html or pdf documents.  This is because the canonical format is xml2rfc so some elements in it could -- and are -- not translated into something visible in the final document).  So I am building a set of unit tests that each takes as input a computerate document and verify that the xml2rfc is correct.

With that in mind, my first meta-comment would be that having a functioning inline `pass:[]` macro would permit to streamline that testing.  As explained below, the xml2rfc elements `<contact/>, <cref/>, and <u/>` have no metanorma-ietf equivalent, but a working pass[] would have permit to at least generate them.  E.g. I tried `pass:[<passthrough format="rfc"><br></passthrough>]` but that did not had the expected result.  FTR Block passthrough works fine, but cannot be used inline.

Another issue I encounter was that anchor attributes are systematically populated with random identifiers, which creates issues when writing unit tests that cannot use explicit identifiers.  Is there a way to disable this or at least make it deterministic?

Now the list of issues:

- Hardbreaks are now supported in xml2rfc with the `<br/>` element, but they are not generated from an inline " +\n".  The [%hardbreaks] paragraph option has the same issue.

- The `<contact>` element cannot be generated from metanorma-ietf.  This is an example of thing that could be generated from a computerate document through the pass macro.

- The `<cref>` element cannot be generated from metanorma-ietf as an inline mark (it can as a block).  An inline version of https://www.metanorma.org/author/ietf/topics/markup/#comments would fix that.  A functioning `pass` could be used as workaround.

- The `<iref>` element is generated, but the text is inserted in front of the `<iref>` element, instead of inside.  That or the documentation at   https://www.metanorma.org/author/ietf/topics/markup/#indexing is wrong.

- The examples in https://www.metanorma.org/author/ietf/topics/markup/#cross-references are a mix of example and syntax.  Same for https://www.metanorma.org/author/ietf/topics/markup/#citations.

- I could not make `<relref>` work according to the syntax in https://www.metanorma.org/author/ietf/topics/markup/#citations:

`<<RFC2119,of>>` results in `<relref target="RFC2119" section="" relative="">of</relref>`, same with comma, parens and bare.

`<<RFC2119,of,section=4.3>>` results in `<relref target="RFC2119" section="" relative="" displayFormat="comma"></relref>`.

`<<RFC2119,of,section-4.3: text>>` results in ``<relref target="RFC2119" section="" relative="" displayFormat="bare">section-4.3: text</relref>.

Finally `<<RFC2119#fragment,of,section-4.3: text>>` is completely rejected.

- The `none` format in `<xref>` is deprecated.

- The `<u>` element is not generated.  A functioning pass macro could be used as workaround.

**Comment by opoudjis** [comment]
Here's a second batch of issues, same methodology but this time about blocks.

- In https://www.metanorma.org/author/ietf/topics/markup/#source-code-listings, the second example does not generate a `<sourcecode>` inside a `<figure>`, but inside a `<t>`.

- In https://www.metanorma.org/author/ietf/topics/markup/#ascii-art-and-images it is said that `<artwork>` occurs only in `<figure>`, which is incorrect.  Like for `<source>`, wrapping a `<artwork>` in a `<figure>` should be explicit.

- In https://www.metanorma.org/author/ietf/topics/markup/#lists, the first example does not generate `<ul><li>`, but `<ul><li><t>`.  Same thing for ordered lists and definition lists.

- About the previous point, I think that when a line in either type of lists is really a single line of text, it should not use the `<t>` wrapper. On the other hand if it is a multiline paragraph or it is mixed with other type of blocks, then `<t>` is appropriate and in fact required.

As before please let me know if I misunderstood something, and what you plan to fix and what you plan to leave as is, so I know what to implement in my fork.

**Comment by opoudjis** [comment]
Implemented `pass-mn:format[]` macro; e.g. `pass-mn:rfc[<u>x</u>]` will deliver RFC XML `<u>x</u>`.

**Comment by opoudjis** [comment]
> Hardbreaks are now supported in xml2rfc with the <br/> element, but they are not generated from an inline " +\n". The [%hardbreaks] paragraph option has the same issue.

https://datatracker.ietf.org/doc/html/draft-levkowetz-xml2rfc-v3-implementation-notes-13#section-3.1.5

Relaxing the original constraints on br appearing only in sourcecode.

**Comment by opoudjis** [comment]
> The <iref> element is generated, but the text is inserted in front of the <iref> element, instead of inside. That or the documentation at https://www.metanorma.org/author/ietf/topics/markup/#indexing is wrong.

The documentation is indeed incorrect: iref has no children.

**Comment by opoudjis** [comment]
@petithug 

> The examples in https://www.metanorma.org/author/ietf/topics/markup/#cross-references are a mix of example and syntax. Same for https://www.metanorma.org/author/ietf/topics/markup/#citations.

Could you spell this out please? The syntax used in those two sections seems to me to be the same as that in the remainder of the page.

**Comment by opoudjis** [comment]
> `<<RFC2119,of>>` results in `<relref target="RFC2119" section="" relative="">of</relref>`, same with comma, parens and bare.

Not a legitimate example, removed from documentation and replaced with `<<RFC2119>>`

> `<<RFC2119,of,section=4.3>>` results in `<relref target="RFC2119" section="" relative="" displayFormat="comma"></relref>`.

Bug, fixed

> `<<RFC2119,of,section-4.3: text>>` results in ``section-4.3: text.`

Typo for `<<RFC2119,of,section=4.3: text>>`. This is processed correctly.

> `<<RFC2119#fragment,of,section-4.3: text>>`

Typo for `<<RFC2119#fragment,of,section=4.3: text>>`. This is now processed correctly.

We have however a new issue: that our generated RFC references are not being recognised by xml2rfc as such.

**Comment by opoudjis** [comment]
Rectified RFC reference recognition: seriesInfo needs to be RFC or Internet-Draft, not IETF

**Comment by opoudjis** [comment]
> In https://www.metanorma.org/author/ietf/topics/markup/#source-code-listings, the second example does not generate a `<sourcecode>` inside a `<figure>`, but inside a `<t>`.

Not replicating: the sourcecode is not inside a t, but a first level child of section. Correcting documentation, this was inherited from RFC XML v2.

**Comment by opoudjis** [comment]
> In https://www.metanorma.org/author/ietf/topics/markup/#ascii-art-and-images it is said that <artwork> occurs only in <figure>, which is incorrect. Like for <source>, wrapping a <artwork> in a <figure> should be explicit.

Fixed documentation.

**Comment by opoudjis** [comment]
> In https://www.metanorma.org/author/ietf/topics/markup/#lists, the first example does not generate `<ul><li>`, but `<ul><li><t>`. Same thing for ordered lists and definition lists.

Fixed documentation.

**Comment by ronaldtse** [comment]
How about a more generic `pass-format:{format}[{content}]` instead of `pass-mn:{format}[{content}]`?

**Comment by opoudjis** [comment]
... What on earth does that buy me?!

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-standoc/issues/24 is our past ticket on content based identifiers; we will revisit. The identifiers will only be stable so long as their content is stable, but that may be enough.

**Comment by ronaldtse** [comment]
I believe content-based identifiers will address @petithug 's concerns about random IDs. Let us know, thanks!

**Comment by opoudjis** [comment]
@petithug: The one feature we will not implement is `contact`, because that is a bit too idiosyncratic to incorporate into our semantics; but we now have both inline and block passthrough for RFC XML.

**Comment by petithug** [comment]
@opoudjis That's fine, it could even be a good example of use of the passthrough in the documentation.

That said it seems that I cannot use a passthough in an appendix (in the contributor section in my case):

Metanorma XML Syntax: (XML Line 004389:28): element "passthrough" not allowed here; expected the element 
end-tag or element "admonition", "bookmark", "clause", "dl", "example", "figure", "form", "formula", "hr"
, "imagemap", "note", "ol", "p", "pagebreak", "permission", "pre", "quote", "recommendation", "requiremen
t", "review", "sourcecode", "svgmap", "table", "toc", "ul" or "variant-title"

**Comment by opoudjis** [comment]
I'm about to update the grammar, working on inline cref now as well.

**Comment by petithug** [comment]
@ronaldtse As long as the ID do not change at each generation of the same document, that's good enough for my needs, which is running tests.

**Comment by petithug** [comment]
@opoudjis Great for the cref.  I am working on a small tool that would extract the cref elements from an Internet-Draft and, together with the info file generated by xml2rfc, will automatically format a review ready to be submitted.  Having cref in metanorma, together with rfc2mn, will make reviewing a document even easier.

**Comment by opoudjis** [comment]
Inline cref to be implemented as block cref + crossreference macro:

````
= X
A
:draft:

ABC cref:[id] DEF

[[id]]
****
comment

comment
****
````

**Comment by petithug** [comment]
Nice.  I am looking forward to use all the improvements in this thread as soon they are released.

**Comment by opoudjis** [comment]
`<u>` rendered by detecting non-ascii characters in text in postprocessing, and wrapping them with `<u></u>` when generating RFC XML. If detailed `<u>` with attributes is needed, switch to passthrough.

**Comment by opoudjis** [comment]
> About the previous point, I think that when a line in either type of lists is really a single line of text, it should not use the `<t>` wrapper. On the other hand if it is a multiline paragraph or it is mixed with other type of blocks, then `<t>` is appropriate and in fact required.

The Metanorma approach is that list items are always paragraphs, for consistency, but I can remove the t wrapper in list items if there is just a single t.

**Comment by opoudjis** [comment]
I'm closing this ticket, as I have now gone through all points raised; I'm keeping https://github.com/metanorma/metanorma-standoc/issues/24 as a separate issue, and I will try to get to it within a fortnight.
