### ISSUE TITLE
Invalid generation for editorial notes

### ISSUE THREAD

**Issue by petithug** [metanorma/metanorma-ietf#164]
This standalone note

```
:draft:

[[id]]
[reviewer="Nick Nicholas",display=true]
.Note Title
****
Profile?!
****
```
Generates xml2rfc source with two errors:

- the title should not be converted into a name element.
- the t element should be outside the cref element, not inside.

Same when referenced by the inline macro cref.

**Comment by ronaldtse** [comment]
Thanks @petithug !
