### ISSUE TITLE
Support RFC new stream "editorial"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#181]
Implement changes to support the new "editorial" stream.

As described here:
* https://github.com/ietf-tools/bibxml-service/issues/301

**Comment by opoudjis** [comment]
I am propagating the editorial stream value along to RFC XML, where it is currently being marked as an error by the xml2rfc validator. The only other thing I can do at the moment is to issue a warning for the requirement that editorial  documents are informational. I'm not seeing any other impact on Metanorma.
