### ISSUE TITLE
Rendering of "ISO/IEC 18014-4" citation seems to lack details

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#190]
From @manuelfuenmayor originally from https://github.com/relaton/relaton-iso/issues/155:

# Description

This:
```
* [[[ISO.IEC.18014-4,ISO/IEC 18014-4]]]
```

renders:
![Screenshot 2023-10-19 194042](https://github.com/relaton/relaton-iso/assets/33627611/64bde39c-7c1c-4acc-9a55-1d93e310e4af)

Problem:
* Title isn't properly shown

A preferred output would be:
![Screenshot 2023-10-19 200730](https://github.com/relaton/relaton-iso/assets/33627611/d430da15-eac9-45b4-9291-9a8e1c89cdc4)

Note that the YEAR shouldn't be shown because this is an "undated reference". If you wanted the year, you would have cited "ISO/IEC 18014-4:2015" instead.

# To reproduce

You can compile the full document in https://github.com/cisba/i-d_dlts/pull/1 (it's not long), or
you can compile this little sample file: [iso-ref.zip](https://github.com/relaton/relaton-iso/files/13048620/iso-ref.zip)

**Comment by opoudjis** [comment]
relaton-render is clearly grabbing the date from the dated instance, not from the root of the document.

**Comment by opoudjis** [comment]
I cannot reproduce this. The RFC I generate has a quite different problem, that the title is only grabbing the intro section:

````
    <references anchor="_informative_references">
      <name>Informative References</name>
      <reference target="https://www.iso.org/standard/59934.html" anchor="ISO.IEC.18014-4">
        <front>
          <title>Information technology</title>
          <author>
            <organization ascii="International Organization for Standardization" abbrev="ISO">International Organization for Standardization</organization>
          </author>
          <author>
            <organization ascii="International Electrotechnical Commission" abbrev="IEC">International Electrotechnical Commission</organization>
          </author>
        </front>
        <format target="https://www.iso.org/standard/59934.html" type="src"></format>
        <format target="https://www.iso.org/obp/ui/en/#!iso:std:59934:en" type="obp"></format>
        <format target="https://www.iso.org/contents/data/standard/05/99/59934.detail.rss" type="rss"></format>
        <refcontent>ISO/IEC 18014-4</refcontent>
      </reference>
    </references>
````


Moreover, https://github.com/cisba/i-d_dlts/ is currently locked to a **Five-Year old** version of metanorma.

I am installing Ruby 2.6.3 (!!!) to see if this is an error specific to the locked version of metanorma-ietf. If it turns out that this failed in 2019 and not 2023, and this was not checked before the ticket made it to me, there will be hell to pay...

**Comment by opoudjis** [comment]
I cannot even install Ruby 2.6.3 on MacOS 14. So now trying to invoke metanorma-ietf 1.0.1, using current Ruby.

**Comment by opoudjis** [comment]
After half an hour of trying  I've given up.

I have tried compiling iso-ref.adoc in the Metanorma PR branch of i-d_dlts, but it does not transfer the date to the reference. Compiling the full document does.

**Comment by opoudjis** [comment]
And that's because  the XML I was looking at... was generated using the four-year old code, not by us.

My time is being wasted here. I am going to debug the issue that is coming up with relation to  RFC XML v3.

**Comment by opoudjis** [comment]
Ok, I'm clearly thoroughly confused here. So:

* v3 current RFC XML is indeed extracting less information than it should. And it turns out that the v3 RFC XML processor references is not going through relaton-render, but is outputting straight to RFC XML.
* I don't particularly *want* to use relaton-render to generate templated RFC XML, but it probably is the best solution, since these are issues already worked out elsewhere.

**Comment by opoudjis** [comment]
As I'm discovering to my astonishment, I had started on that refactor in February, but never tied it back to operating code.

**Comment by opoudjis** [comment]
I need to do some cleanup to port across all the information that was being carried across before, but I am now generating:

````
  <back>
    <references anchor="_informative_references">
      <name>Informative references</name>
      <reference target="https://www.iso.org/standard/59934.html" anchor="ISO.IEC.18014-4"><front><title>Information technology - Security techniques - Time-stamping services</title><author surname="Unknown"></author> <organization>International Organization for Standardization</organization> <organization>International Electrotechnical Commission</organization> </front> <format target="https://www.iso.org/standard/59934.html" format="src"></format><format target="https://www.iso.org/obp/ui/en/#!iso:std:59934:en" format="obp"></format><format target="https://www.iso.org/contents/data/standard/05/99/59934.detail.rss" format="rss"></format></reference>
    </references>
  </back>
````

The `<author surname="Unknown"></author>` is required by IETF. That corresponds to the information requested.

Keeping this issue open as the issue for migrating to relaton-render.
