### ISSUE TITLE
Restructure asciidoctor-rfc to the Metanorma structure

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#2]
Refactor asciidoctor-rfc into the same structure as asciidoctor-iso and asciidoctor-gb.

**Comment by abunashir** [comment]
@ronaldtse: I see a recent commit from you, is the change to metanorma re-structure done? do you still want me to look into this one?

**Comment by ronaldtse** [comment]
I’ve migrated the gem to fit into the new structure, but everything said by @opoudjis is still to be done. 

So please help with this. Thanks!

**Comment by ronaldtse** [comment]
Nice! As mentioned above by @opoudjis, we don’t need to implement Metanorma XML -> HTML / TXT output , those are supported by IETF’s own tools. Ie. Metanorma XML -> RFC XML v2/3 -> HTML / TXT (via the “xml2rfc“ tool).

**Comment by abunashir** [comment]
Hi @ronaldtse, I'm trying to familiarize myself with the document structure, how different is the `ieft` document compare to an `iso` document?

When we will map this one to intermediate `isoxml` then    what are `ieft` specific attributes that's differe from the strandard document? For example we have this doc for [gb-specific-attributes](https://github.com/riboseinc/metanorma-gb#differences-from-metanorma-iso), [csd-specific-attributes](https://github.com/riboseinc/metanorma-csd#attributs-specific-to-csd), do we already have something like this for ieft as well?

Let me know if there is something, it will save me something or I will try to figure it out comparing those docments :)  Thanks.

**Comment by ronaldtse** [comment]
Elements in an `IETF` document is a subset of ISO, so technically we don't need to implement extra custom elements for it. I think the only special attributes are the author addresses. Can @opoudjis confirm?

**Comment by opoudjis** [comment]
Obsoleted by #47
