### ISSUE TITLE
References not filled in

### ISSUE THREAD

**Issue by douglm** [metanorma/metanorma-ietf#209]
I have this in an rfc source:

* [[[RFC9253,RFC 9253]]]
which results in 

   [RFC9253]  "", RFC 9253, RFC 9253,
              <https://www.rfc-editor.org/rfc/rfc9253>.

Is there something I need to do to get this updated?

**Comment by douglm** [comment]
So I did discover the cache in ~/.relaton/cache/ietf/

I renamed the not found entry for rfc9253 which was dated Feb 15 this year and reran metanorma and I see the messages

[relaton-ietf] ("RFC 9253") fetching...
[relaton-ietf] ("RFC 9253") not found

This RFC was published in August 2022 so is there something special about this rfc or are we not seeing any new ones?

In the meantime can I manually specify the information - the draft I am producing is in last call so this is fairly urgent.

**Comment by ronaldtse** [comment]
@douglm I was able to fetch it via Relaton:

```sh
$ bundle exec relaton fetch "RFC 9253"
[relaton-ietf] (RFC 9253) Fetching from Relaton repository ...
[relaton-rfc] Downloaded index from https://raw.githubusercontent.com/relaton/relaton-data-rfcs/main/index-v1.zip
[relaton-ietf] (RFC 9253) Found: `RFC 9253`
<bibdata type="standard" schema-version="v1.2.8">
  <fetched>2024-04-06</fetched>
  <title type="main" format="text/plain">Support for iCalendar Relationships</title>
  <uri type="src">https://www.rfc-editor.org/info/rfc9253</uri>
  <docidentifier type="IETF" primary="true">RFC 9253</docidentifier>
```

What's the version of Metanorma you're using? Can you point me to the repo so I can check it out? Thanks!

**Comment by ronaldtse** [comment]
@douglm the references are correctly filled as in:
* https://github.com/CalConnect/PUBLIC_DRAFTS/pull/27

<img width="696" alt="image" src="https://github.com/metanorma/metanorma-ietf/assets/11865/f901188c-046f-49ae-a88b-1d0afbb3d6ed">
