### ISSUE TITLE
Use VCR to mock network calls

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-ietf#21]
To make tests more stable maybe make sense to add VCR (https://travis-ci.org/metanorma/metanorma-ietf/jobs/522671392)

cc @opoudjis @ronaldtse 

P.S. I can help if need

**Comment by ronaldtse** [comment]
@CAMOBAP795 agree, please go ahead.

**Comment by opoudjis** [comment]
@CAMOBAP795 reminder: I am no longer maintaining metanorma-ietf; @abunashir has a long-term project underway to migrate it from Asciidoctor > RFC XML to Asciidoctor > Metanorma XML > RFC XML, to align it with our other gems. For any queries relating to metanorma-ietf, please inform him.

**Comment by ronaldtse** [comment]
@CAMOBAP795 please help if you can. Thanks!
