### ISSUE TITLE
Numbered Abstract

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ietf#210]
From https://github.com/metanorma/rfc-asciidoc-rfc/issues/26:

Hi people, today I uploaded to IETF the draft https://github.com/cisba/i-d_dlts and got the error "The Abstract section seems to be numbered" (see original long output below).

This error seems related to the new template used by Metanorma and it is really a big issue because it is blocking the submission process to IETF.

@ronaldtse @manuelfuenmayor 

`Submission rejected: Checks failed: idnits 2.17.00 (12 Aug 2021) /a/www/www6s/staging/draft-intesigroup-dlts-08.txt: ** The Abstract section seems to be numbered Showing Errors (**), Flaws (~~), Warnings (==), and Comments (--). Errors MUST be fixed before draft submission. Flaws SHOULD be fixed before draft submission. Checking boilerplate required by [RFC 5378](https://datatracker.ietf.org/doc/rfc5378/) and the IETF Trust (see https://trustee.ietf.org/license-info): ---------------------------------------------------------------------------- No issues found here. Checking nits according to https://www.ietf.org/id-info/1id-guidelines.txt: ---------------------------------------------------------------------------- No issues found here. Running in submission checking mode -- *not* checking nits according to https://www.ietf.org/id-info/checklist . ---------------------------------------------------------------------------- Summary: 1 error (**), 0 flaws (~~), 0 warnings (==), 0 comments (--).`

**Comment by opoudjis** [comment]
@cisba I have compiled this locally and there was no nit issue with xml2rfc 3.21. It is hard for me to know what is going on if IETF's tools are not going to warn me locally, you may want to take this up with them . 

The abstract is currently encoded as

````
<section anchor="_abstract"><name>Abstract</name>
 
<t anchor="_7d7af469-c146-4a97-4657-1faf77f0aa8a">This document defines a standard to extend Time Stamp Tokens
with Time Attestations recorded on Distributed Ledgers.</t>
      
<t anchor="_ec0eb48d-4d35-f40f-42b5-4c72152c6adb">The aim is to provide long-term validity to Time Stamp Tokens,
backward compatible with currently available software.</t>
</section>
````

ie. as just a normal section --- because you have encoded it in Asciidoc as just a normal section.

````
== Abstract

This document defines a standard to extend Time Stamp Tokens
with Time Attestations recorded on Distributed Ledgers.

The aim is to provide long-term validity to Time Stamp Tokens,
backward compatible with currently available software.
````

My guess is, IETF has introduced a nit for "Abstract" as the title of a normal section. Which this currently is. Try marking it up as an actual abstract in Asciidoc:

````
[abstract]
== Abstract
````

When I do that, I get:

````
    <abstract anchor="_abstract"><t anchor="_469ae2e4-966f-7430-6c19-582668b61421">This document defines a standard to extend Time Stamp Tokens
with Time Attestations recorded on Distributed Ledgers.</t>

<t anchor="_9b56c736-1543-2b17-9a7d-21c112ae52ed">The aim is to provide long-term validity to Time Stamp Tokens,
backward compatible with currently available software.</t>
</abstract>
````

Which is what I expect.

The mn-templates-ietf template for RFC does correctly markup Abstracts, so this issue did not originate from the templates, contra your suggestion in the ticket:

````
[[abstract-id]]
[abstract]
== Abstract
This document provides a template on how to author (or migrate!)
a new Internet-Draft / RFC in the AsciiRFC format.

NOTE: This template requires usage of the Metanorma toolchain and the
  `metanorma-ietf` Ruby gem.                                 
````

Please confirm that this works.

**Comment by cisba** [comment]
Yes, it works fine. I added just the [abstract] line and it fixed it.
Thanks!
