### ISSUE TITLE
Metanorma update from 1.10.1 to 1.11.1 fails compiling I-D

### ISSUE THREAD

**Issue by cisba** [metanorma/metanorma-ietf#215]
Metanorma update from 1.10.1 to 1.11.1 fails compiling Internet draft [dlts](https://github.com/cisba/i-d_dlts).

Output last message:
/home/user/devel/i-d_dlts/draft-intesigroup-dlts.rfc.xml(9): Error: Invalid document before running preptool.
Unable to complete processing /home/user/devel/i-d_dlts/draft-intesigroup-dlts.rfc.xml

Files err.xml attached here:
[r1.10.1_draft-intesigroup-dlts.err.html.txt](https://github.com/user-attachments/files/17881504/r1.10.1_draft-intesigroup-dlts.err.html.txt)
[r1.11.1_draft-intesigroup-dlts.err.html.txt](https://github.com/user-attachments/files/17881568/r1.11.1_draft-intesigroup-dlts.err.html.txt)

**Comment by opoudjis** [comment]
I found the issue, and I'm surprised it hadn't surfaced before now: `dt/@id` in Metanorma XML was not transforming correctly into `dt/@anchor`.

I'll fix this now, but we aren't scheduled for another release for two weeks. Until the release, you can use the updated code to compile the file by creating the file `Gemfile` in the i-d_dlts directory:

````
source "https://rubygems.org"

gem "metanorma-cli"
gem "metanorma-ietf", git: "https://github.com/metanorma/metanorma-ietf", branch: "main"
````

And running

````
bundle update
bundle exec metanorma site generate
````

Confirmed bug and fix with latest version of xml2rfc. Please confirm this is working for you.

**Comment by cisba** [comment]
I updated metanorma by snap at release 1.11.2. Now it works fine. Thanks
