### ISSUE TITLE
Bugs in XML generation

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#22]
@opoudjis , Metanorma-IETF is generating problematic RFC XML in https://github.com/CalConnect/csd-vpoll/pull/1

Specifically, `xml2rfc` complains:

```
Error: Unable to validate the XML document: /var/folders/lb/lnnfrqr92_g1dp5qlr769gzw0000gp/T/draft-york-vpoll.txt20190516-77339-1yat92d
 <string>: Line 529: Element figure content does not follow the DTD, expecting (iref* , preamble? , artwork , postamble?), got nothing.
 <string>: Line 558: Element figure content does not follow the DTD, expecting (iref* , preamble? , artwork , postamble?), got nothing.
 <string>: Line 2500: Element new-prop-para-required is not declared in c list of possible children
 <string>: Line 2500: No declaration for element new-prop-para-required
 <string>: Line 2503: Element new-prop-para-stay-informed is not declared in c list of possible children
 <string>: Line 2503: No declaration for element new-prop-para-stay-informed
 <string>: Line 2513: Element new-prop-reply-url is not declared in c list of possible children
 <string>: Line 2513: No declaration for element new-prop-reply-url
 <string>: Line 2516: Element new-prop-poll-item-id is not declared in c list of possible children
 <string>: Line 2516: No declaration for element new-prop-poll-item-id
 <string>: Line 2519: Element new-prop-poll-mode is not declared in c list of possible children
 <string>: Line 2519: No declaration for element new-prop-poll-mode
 <string>: Line 2522: Element new-prop-poll-properties is not declared in c list of possible children
 <string>: Line 2522: No declaration for element new-prop-poll-properties
 <string>: Line 2525: Element new-prop-poll-winner is not declared in c list of possible children
 <string>: Line 2525: No declaration for element new-prop-poll-winner
 <string>: Line 2528: Element new-prop-response is not declared in c list of possible children
 <string>: Line 2528: No declaration for element new-prop-response
 <string>: Line 2531: Element new-prop-voter is not declared in c list of possible children
 <string>: Line 2531: No declaration for element new-prop-voter
```

Line 529 is due to the stray `<figure/>` element (if I remove it, it works)
<img width="647" alt="Screen Shot 2019-05-16 at 2 36 35 AM" src="https://user-images.githubusercontent.com/11865/57800218-6d51a880-7783-11e9-92f9-1d454bbacfff.png">

Line 558 as well:

<img width="178" alt="Screen Shot 2019-05-16 at 2 37 13 AM" src="https://user-images.githubusercontent.com/11865/57800253-84909600-7783-11e9-8710-9000e5f3b5c4.png">

Line 2500, etc., are due to failure in resolving anchors -- it's treating <<xx>> brackets as actual text.

<img width="564" alt="Screen Shot 2019-05-16 at 2 37 34 AM" src="https://user-images.githubusercontent.com/11865/57800301-aab63600-7783-11e9-8c24-c3576ec2d6dc.png">

**Comment by opoudjis** [comment]
There are errors and missteps in Asciidoctor in this document. To have me be the one debugging them instead of the author is regrettable.

The use of `[example]` with no delimiter, but with continuation blocks, as in:

````
[example]
in BASIC poll-mode, reaching the DTEND of the poll
could trigger this server side action.
+
Server initiated submission requires that the submitted choice
MUST be a valid calendaring component.
+
POLL-COMPLETION=SERVER-SUBMIT allows the client to set the poll-
winner, set the status to CONFIRMED and then store the poll on the
server.  The server will then submit the winning choice and set
the status to SUBMITTED.
````

is something Asciidoctor has difficulty with, to the extent that it fails to recognise even the first paragraph as an example: that's why the `<figure/>` tag is closed prematurely. This is remedied by inserting the not-so-optional example delimiters `====` around the examples. Any concerns about needing to do so are a matter for Asciidoctor, not Metanorma.

**Comment by ronaldtse** [comment]
@opoudjis an interesting reminder -- you and I were the ones who did the original conversion 😉 

This is why we must fully parse the document using Asciidoctor into our document model before serializing anything out.

**Comment by opoudjis** [comment]
The refusal to process formatting in table cells is because of a v2 constraint on not permitting blocks in cells; the content of cells is being processed as cell.text, not cell.content.

... In retrospect (two years of retrospect), the code shouldn't be doing that  intervention here (and it's backfiring anyway). I will parse the table cell contents fulls as cell.content; if there is a parse error because the table has been formatted to include content illegal according to RFC XML, that needs to be discovered at the RFC XML output, not second guessed beforehand.

**Comment by opoudjis** [comment]
> This is why we must fully parse the document using Asciidoctor into our document model before serializing anything out.

That is either done under the aegis of the metanorma-ietf upgrade to Metanorma XML (which I am not going to be involved in), or it is a request to add Metanorma XML conversion as internal validation on top of the current Asciidoctor > RFC XML functionality (which is duplicating the metanorma-ietf upgrade to Metanorma XML, and which I'm not going to be involved in either.)

**Comment by opoudjis** [comment]
These two parse errors have been addressed, and a new bunch of errors are now being reported.

````
[metanorma-ietf] element "preamble" not allowed here; expected element "artwork" @ 517:13
[metanorma-ietf] element "preamble" not allowed here; expected element "artwork" @ 520:13
[metanorma-ietf] element "figure" incomplete; missing required element "artwork" @ 525:10
[metanorma-ietf] element "preamble" not allowed here; expected element "artwork" @ 550:13
````

Metanorma-ietf expects that examples are going to be :listing, :image, :literal, :stem. It does not expect prose in there, and it expects any prose in there to be preambles before a listing, :image, :literal, :stem. Hence, the prose-only example has just preambles in it, and no artwork.

I don't think this error is wrong: it shows that Metanorma is generating structures that RFC XML does not expect to see, and it is right to say that. The markup is legal Asciidoctor, but in lacking source code, image, ascii art or a math formula, it *is* illegal RFC XML. The mark up should be fixed, and the RFC XML is doing its job.

**Comment by ronaldtse** [comment]
> That is either done under the aegis of the metanorma-ietf upgrade to Metanorma XML 

It is why we need to do exactly that.

> You're going to have to tell me what you intended here. Example is not appropriate for RFC XML.

The point is: a Metanorma AsciiDoc should be processable into valid CSD and valid RFC XML. The RFC XML errors are not wrong -- it is what we generate that is wrong.

**Comment by opoudjis** [comment]
Am detecting examples that have only text content in them, and treating them as paragraph text in v2 RFC XML instead of as examples. This is a one-off fix; the reengineering is a big project that I am not undertaking.
