### ISSUE TITLE
column width values need to be rounded

### ISSUE THREAD

**Issue by douglm** [metanorma/metanorma-ietf#23]
Setting relative column widths can break the xml2rfc conversion to text as the width is output as a decimal number with a fractional part. MUST be integer followed by '%'

**Comment by ronaldtse** [comment]
This is from https://github.com/CalConnect/csd-vpoll

ADoc:
<img width="322" alt="Screen Shot 2019-05-17 at 1 18 04 AM" src="https://user-images.githubusercontent.com/11865/57873756-a0f30800-7841-11e9-9fda-df904f82fca0.png">


XML:
<img width="497" alt="Screen Shot 2019-05-17 at 1 07 09 AM" src="https://user-images.githubusercontent.com/11865/57873190-1a89f680-7840-11e9-8b1a-547b508bbb92.png">
