### ISSUE TITLE
List headers separated from content

### ISSUE THREAD

**Issue by douglm** [metanorma/metanorma-ietf#24]
The generated xml for a list is this:

````
<t hangText="DTSTAMP"><vspace blankLines="0"/>The usual <xref target="RFC5545"/> property.</t>
````

whereas it was

````
<t hangText="DTSTAMP:">
  The usual <xref target='RFC5545'/> property.
</t>
````

I don't have much opinion one way or the other as to style but it does lead to the problem below

````
   Purpose

York, et al.            Expires November 16, 2019              [Page 18]

Internet-Draft                    VPOLL                         May 2019

      This property may be used in scheduling messages to indicate
      additional reply methods, for example a web-service.
````

The list header ("Purpose") is getting detached from the text. Is there a way to force the header to stay with the associated text?

**Comment by opoudjis** [comment]
As I noted in the code, the added vspace in a definition list is extraneous to the RFC XML spec, but is required by IDNITS. 

This is automated XML generation, so either all definition list single paragraphs (like this) have a blank space before them, or none of them do.  I strongly suspect that the workflow into xml2rfc is presupposing some manual post-editing of the XML.

**Comment by ronaldtse** [comment]
This is an unfortunate flaw / incompatibility between xml2rfc and idnits. 

As mentioned by @opoudjis , idnits complains on a lack of vspace between a DT and DD. But indeed insertion of that will cause xml2rfc to potentially make a page break. 

The best way to move ahead with preventing this break is to have an option to not generate the “vspace”. The caveat is that idnits will complain. 

Would this work for you @douglm ?

**Comment by douglm** [comment]
I'm fine with whatever will generate least work.

We can leave things where they are for the moment

**Comment by ronaldtse** [comment]
Then let's do an option that omits the insertion of the `<vspace>` between `<dt>` and `<dd>` in RFC XML output. That should be straightforward.

@opoudjis does that sound reasonable?

**Comment by opoudjis** [comment]
Well, I think by the end there are going to be a mountain of options, but OK. This in particular does deserve it.

@douglm I try to restrict gem releases to fortnightly; will you be OK to download from github as I go?

**Comment by opoudjis** [comment]
It turns out this functionality is already supported: add document attribute `:inline-definition-lists:` to the document header.

(I had thought this was going to impact the XML output  as a preprocessing instruction, which is why I didn't mention it, but it turns out it is specific to this context only.)

**Comment by ronaldtse** [comment]
@opoudjis darn -- it was implemented 2 years ago (https://github.com/metanorma/metanorma-ietf/commit/b1f036bb560b8f6c1eb277b5561b75fe93a40cf5). Apparently we had the same need before.

And it's documented too:
https://www.metanorma.com/author/ietf/ref/document-attributes/

**Comment by opoudjis** [comment]
I prefer to think of it as: I anticipated the need. Of course, it was two years ago, so I completely forgot I had.

**Comment by douglm** [comment]
Thanks - I've been out for the weekend but I'll give this a try

**Comment by douglm** [comment]
I've lost count of the times I start implementing something and discover 
I already did it
