### ISSUE TITLE
admonition treatment

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ietf#25]
RFC Asciidoctor and Metanorma Asciidoctor are not designed to be compatible, and making them compatible is a major undertaking I will not be undertaking. There is a distinct initiative to refactor this gem to align it to Metanorma Asciidoctor, assigned to @abunashir, which is currently on hold.

This ticket is to do a piecemeal update to metanorma-ietf: instead of rendering admonitions as `cref` elements (which correspond to Metanorma reviewer notes), they will be rendered as NOTE (or whatever the admonition type is), followed by the text of the admonition as blocks. This update will only be done to v2, as v3 appears to be inactive.

This change means that metanorma-ietf (as opposed to the existing asciidoctor-rfc) will no longer support cref. A future port of Metanorma will instead support cref as Metanorma reviewernote.

**Comment by opoudjis** [comment]
I have added this to metanorma.com documentation. I am reluctant to fix the rspec of this gem to match: this gem has now fallen off the deep end anyway.

**Comment by ronaldtse** [comment]
@opoudjis please help add a spec for this; otherwise this fix will truly drop from the face of the earth on the upcoming refactor.
