### ISSUE TITLE
More space between table rows

### ISSUE THREAD

**Issue by douglm** [metanorma/metanorma-ietf#26]
Tables displayed in other than ietf ascii have some space between rows.

This used to be accomplished for rfcs in hand-crafted XML by adding an empty row. So in hand crafted form we'd get:

     | Method         | Description                                      |
     +----------------+--------------------------------------------------+
     | PUBLISH        | No changes (yet)                                 |
     |                |                                                  |
     | REQUEST        | Each child component MUST have a POLL-ITEM-ID    |

in metanorma we get

     | Method         | Description                                      |
     +----------------+--------------------------------------------------+ 
     | PUBLISH        | No changes (yet)                                 |
     | REQUEST        | Each child component MUST have a POLL-ITEM-ID    |

**Comment by ronaldtse** [comment]
It supports adding empty rows in the table to achieve the same effect, but it somewhat waters down the semantics of the generated XML...

Original code:
```adoc
[cols="a,a",options="header"]
|===
| Method
| Description

| PUBLISH        | No changes (yet)

| REQUEST        | Each child component MUST have a POLL-ITEM-ID
property.  Each set of components with the same
POLL-ITEM-ID value represents one overall set of
items to be voted on.
```

Empty row added:
```
[cols="a,a",options="header"]
|===
| Method
| Description

| PUBLISH        | No changes (yet)
|                |
| REQUEST        | Each child component MUST have a POLL-ITEM-ID
property.  Each set of components with the same
POLL-ITEM-ID value represents one overall set of
items to be voted on.
```

**Comment by ronaldtse** [comment]
Closing since this is a presentation issue.
