### ISSUE TITLE
Extract RFC bib fetching / caching / citation functionality into `rfcbib`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#3]
This work is to extract the RFC/I-D bibliographic information fetching / caching / citation functionality into https://github.com/riboseinc/rfcbib/.

**Comment by opoudjis** [comment]
Oh wow. It's been two years.

https://github.com/metanorma/metanorma-ietf/blob/master/lib/asciidoctor/rfc/common/base.rb

cache_biblio(), insert_biblio()

**Comment by andrew2net** [comment]
@ronaldtse in the test there is a reference `ISO.IEC.10118-3`, but I don't see such a reference on any of pages:
https://xml2rfc.tools.ietf.org/public/rfc/bibxml
https://xml2rfc.tools.ietf.org/public/rfc/bibxml2
https://xml2rfc.tools.ietf.org/public/rfc/bibxml3
https://xml2rfc.tools.ietf.org/public/rfc/bibxml4
https://xml2rfc.tools.ietf.org/public/rfc/bibxml5
https://xml2rfc.tools.ietf.org/public/rfc/bibxml6
Is the reference correct? Ther we can fetch it form?

**Comment by ronaldtse** [comment]
@andrew2net ISO/IEC 10118-3 of course should be fetched via relaton-iso 😉
