### ISSUE TITLE
create IETF template

### ISSUE THREAD

**Issue by wsdwl** [metanorma/metanorma-ietf#30]
It would be nice to be able to create an IETF document in the same way, as it is possible with csd and ISO described here: https://www.metanorma.com/blog/2019-04-26-metanorma-templates-and-metanorma-new/

Would help a lot in the CalConnect  group to increase the usage and migration of drafts being worked on.

**Comment by ronaldtse** [comment]
Thanks @wsdwl , we will get it done this weekend!

**Comment by ronaldtse** [comment]
Pending: https://github.com/metanorma/metanorma-cli/issues/93

**Comment by ronaldtse** [comment]
@wsdwl sorry for the late reply, apparently it's been done some time ago 👍 

The way to execute it is:
```sh
metanorma new -t ietf -d rfc my-document
```

Thanks!
