### ISSUE TITLE
Bug: During `xml2rfc`, ENTITY file cannot use gem's rfc2629.dtd path

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#33]
Right now, the XML file generated contains these lines:

```xml
<?xml-stylesheet type="text/xsl" href="rfc2629.xslt"?>
<!DOCTYPE rfc SYSTEM "/Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-ietf-1.0.4/rfc2629.dtd" [
```

When I run `xml2rfc`, it fails like this:

```sh
me:~/tmp/ACVP/drbg (master *): xml2rfc draft-vassilev-acvp-drbg.xml 
Parsing file draft-vassilev-acvp-drbg.xml
Error: Unable to validate the XML document: draft-vassilev-acvp-drbg.xml
 <string>: Line 1: No declaration for attribute base of element reference
 <string>: Line 1: No declaration for attribute base of element reference
 <string>: Line 1: No declaration for attribute base of element reference
```

But when I return the DTD file to local scope (how it was before):

```xml
<?xml-stylesheet type="text/xsl" href="rfc2629.xslt"?>
<!DOCTYPE rfc SYSTEM "rfc2629.dtd" [
```

`xml2rfc` works!

```sh
me:~/tmp/ACVP/drbg (master *): xml2rfc draft-vassilev-acvp-drbg.xml 
Parsing file draft-vassilev-acvp-drbg.xml
Warning: Text around line 730 contains tab characters.  These will be expanded, assuming a tab-size of 8.
Warning: Text around line 752 contains tab characters.  These will be expanded, assuming a tab-size of 8.
Warning: so many <ttcol>s in <texttable> that some words need to be split near line 85
Warning: Text around line 730 contains tab characters.  These will be expanded, assuming a tab-size of 8.
Warning: Text around line 752 contains tab characters.  These will be expanded, assuming a tab-size of 8.
Warning: no <xref> in <rfc> targets <reference anchor='ACVP'>
Warning: no <xref> in <rfc> targets <reference anchor='DRBGVS'>
Warning: no <xref> in <rfc> targets <reference anchor='RFC7991'>
Created file draft-vassilev-acvp-drbg.txt
me:~/tmp/ACVP/drbg (master *): xml2rfc draft-vassilev-acvp-drbg.xml 
```

@CAMOBAP795 this is urgent. Can you help fix this ASAP? I'm not sure if we even need to actually point to the rfc2629.dtd file. The code seems to work even if there is no local rfc2629.dtd.

Can you revert this change?

The document in question is here:
https://github.com/metanorma/ACVP/tree/fix-metanorma/drbg

Run with this command:
```
metanorma draft-vassilev-acvp-drbg.adoc
```

**Comment by CAMOBAP795** [comment]
@ronaldtse on it

**Comment by CAMOBAP795** [comment]
@ronaldtse I think there is a better solution than just reverting https://github.com/metanorma/metanorma-ietf/commit/a3f3f8f85f60e045af73d7c8fe7e7dcde2b4a45b because we will break `Jing` validation back

### Investigation

I have reproduced the issue locally

The problem that according to provided "rfc2629.dtd" which is bundled into `metanorma-ietf-1.0.4` this document really invalid

But when you change "/Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-ietf-1.0.4/rfc2629.dtd" -> "rfc2629.dtd" this force `xml2rfc` use internal dtd

---

### Proposed solution

According to https://www.tutorialspoint.com/dtd/dtd_syntax

> DTD identifier is an identifier for the document type definition, which may be the path to a file on the system **__or URL to a file on the internet__**. If the DTD is pointing to external path, it is called external subset.

So we didn't violate the formal rules

I propose 2 ways:
 - use URL to "rfc2629.dtd" instead "rfc2629.dtd"
 - update "rfc2629.dtd" inside of `metanorma-ietf` gem

I think the first solution is better, I just need to find trustful URL

@ronaldtse how do you think about this maybe you can suggest something?

**Comment by ronaldtse** [comment]
1. How is this document invalid? We should not be generating an invalid document. 

2. We can point to https://raw.githubusercontent.com/metanorma/metanorma-ietf/master/rfc2629.dtd directly for the DTD location. 

3. How do you know xml2rfc is using an internal DTD? The “local” DTD is identical to the one inside metanorma-ietf .  If the xml2rfc has an internal DTD, we should update ours to the xml2rfc one.

**Comment by CAMOBAP795** [comment]
> 1. How is this document invalid? We should not be generating an invalid document.

To be honest, I'm not an expert in DTD, but as I understand the error message `<string>: Line 1: No declaration for attribute base of element reference` We use somewhere `base` in our xmls

I have `grep`ed:
 - local XMLs
 - remote ones (like https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml)

No success... then I paid attention to this:

```
...
Resolving entity... https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml
Loaded from cache /Users/camobap/.cache/xml2rfc/reference.RFC.2119.xml
...
```

And 

```
grep -R base /Users/camobap/.cache/xml2rfc/reference.RFC.2119.xml
/Users/camobap/.cache/xml2rfc/reference.RFC.2119.xml:<reference anchor="RFC2119" target="https://www.rfc-editor.org/info/rfc2119" xml:base="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml">
```

So looks like xml2rfc preprocess somehow `reference.RFC.XXX.xml` before saving to cache (@ronaldtse let me know if I should look deeper)

> 2.  We can point to https://raw.githubusercontent.com/metanorma/metanorma-ietf/master/rfc2629.dtd directly for the DTD location.

Ok, but in comparison with xml2rfc's one it looks outdated

<details><summary>This is diff between rfc2629.dtd from metanorma-ietf vs rfc2629.dtd from xml2rfc</summary>
<p>

```
--- /Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/metanorma-ietf-1.0.3/rfc2629.dtd	2019-06-18 11:51:10.000000000 +0300
+++ /usr/local/lib/python3.7/site-packages/xml2rfc/templates/rfc2629.dtd	2019-07-20 11:14:39.000000000 +0300
@@ -83,7 +83,7 @@
 
 <!ENTITY % TEXT       "#PCDATA">
 
-<!ENTITY   rfc.number "XXXX">
+<!ENTITY   rfc.number SYSTEM "internal:/rfc.number">
 
 
 <!--
@@ -152,10 +152,18 @@
      elements may be present -->
 <!ELEMENT postal      (street+,(city|region|code|country)*)>
 <!ELEMENT street      (%CTEXT;)>
+<!ATTLIST street
+          ascii       %ATEXT;            #IMPLIED>
 <!ELEMENT city        (%CTEXT;)>
+<!ATTLIST city
+          ascii       %ATEXT;            #IMPLIED>
 <!ELEMENT region      (%CTEXT;)>
+<!ATTLIST region
+          ascii       %ATEXT;            #IMPLIED>
 <!ELEMENT code        (%CTEXT;)>
 <!ELEMENT country     (%CTEXT;)>
+<!ATTLIST country
+          ascii       %ATEXT;            #IMPLIED>
 <!ELEMENT phone       (%CTEXT;)>
 <!ELEMENT facsimile   (%CTEXT;)>
 <!ELEMENT email       (%CTEXT;)>
@@ -189,6 +197,7 @@
 <!ATTLIST section
           anchor      ID                 #IMPLIED
           title       %ATEXT;            #REQUIRED
+	  numbered    (yes|no|true|false) "true"
           toc         (include|exclude|default)
                                          "default">
 
@@ -202,7 +211,7 @@
   -->
 
 <!-- use of <figure/> is deprecated... -->
-<!ELEMENT t           (%TEXT;|list|figure|xref|eref|iref|cref|spanx|vspace)*>
+<!ELEMENT t           (%TEXT;|list|figure|xref|eref|iref|cref|spanx|vspace|u)*>
 <!ATTLIST t
           anchor      ID                 #IMPLIED
           hangText    %ATEXT;            #IMPLIED>
@@ -257,7 +266,7 @@
           width       %ATEXT;            ""
           height      %ATEXT;            "">
 
-<!ELEMENT preamble    (%TEXT;|xref|eref|iref|cref|spanx)*>
+<!ELEMENT preamble    (%TEXT;|xref|eref|iref|cref|spanx|u)*>
 <!ELEMENT artwork     (%TEXT;)*>
 <!ATTLIST artwork
           xml:space   (default|preserve) "preserve"
@@ -269,7 +278,7 @@
           width       %ATEXT;            ""
           height      %ATEXT;            "">
 
-<!ELEMENT postamble   (%TEXT;|xref|eref|iref|cref|spanx)*>
+<!ELEMENT postamble   (%TEXT;|xref|eref|iref|cref|spanx|u)*>
     
 <!ELEMENT texttable   (preamble?,ttcol+,c*,postamble?)>
 <!ATTLIST texttable
@@ -282,7 +291,7 @@
 <!ATTLIST ttcol
           width       %ATEXT;            #IMPLIED
           align       (left|center|right) "left">
-<!ELEMENT c           (%TEXT;|xref|eref|iref|cref|spanx)*>
+<!ELEMENT c           (%TEXT;|xref|eref|iref|cref|spanx|u)*>
 
 
 <!--
@@ -298,7 +307,9 @@
           title       %ATEXT;            "References">
 <!ELEMENT reference   (front,seriesInfo*,format*,annotation*)>
 <!ATTLIST reference
+	  quote-title (true|false)	 "true"
           anchor      ID                 #IMPLIED
+          xml:base    %ATEXT;            #IMPLIED
           target      %URI;              #IMPLIED>
 <!ELEMENT seriesInfo  EMPTY>
 <!ATTLIST seriesInfo
@@ -309,4 +320,9 @@
           target      %URI;              #IMPLIED
           type        %ATEXT;            #REQUIRED
           octets      %NUMBER;           #IMPLIED>
-<!ELEMENT annotation  (%TEXT;|xref|eref|iref|cref|spanx)*>
+<!ELEMENT annotation  (%TEXT;|xref|eref|iref|cref|spanx|u)*>
+<!ELEMENT u	      (%TEXT;)>
+<!ATTLIST u
+          anchor      ID                 #IMPLIED
+          ascii       %ATEXT;            #IMPLIED
+          format      %ATEXT;            #IMPLIED>
```
</p>
</details>

> 3. How do you know xml2rfc is using an internal DTD?  The “local” DTD is identical to the one inside metanorma-ietf . If the xml2rfc has an internal DTD, we should update ours to the xml2rfc one.

According to logs from `xml2rfc --verbose draft-vassilev-acvp-drbg.xml` if I change the absolute path to DTD to "local" one it reports

```
Parsing file draft-vassilev-acvp-drbg.xml
Resolving entity... /usr/local/lib/python3.7/site-packages/xml2rfc/templates/rfc2629.dtd
Resolving entity... /usr/local/lib/python3.7/site-packages/xml2rfc/templates/rfc2629-xhtml.ent
Resolving entity... /usr/local/lib/python3.7/site-packages/xml2rfc/templates/rfc2629-other.ent
Resolving entity... /usr/local/lib/python3.7/site-packages/xml2rfc/templates/rfc2629.dtd
Resolving entity... /usr/local/lib/python3.7/site-packages/xml2rfc/templates/rfc2629-xhtml.ent
Resolving entity... /usr/local/lib/python3.7/site-packages/xml2rfc/templates/rfc2629-other.ent
Resolving entity... https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml
Loaded from cache /Users/camobap/.cache/xml2rfc/reference.RFC.2119.xml
...

----

Let me summarize here is my proposal to solve the problem https://github.com/metanorma/metanorma-ietf/pull/35

**Comment by ronaldtse** [comment]
#35 has been merged. @CAMOBAP795 can you confirm that the `xml2rfc --verbose draft-vassilev-acvp-drbg.xml` command now works? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse works when I tested locally, but we need to release new version of gem with this logic to fix it for users

**Comment by ronaldtse** [comment]
Got it. Could you also test the git version just to be sure? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse  Confirmed

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 , do we need a new release of `metanorma-ietf`?

**Comment by CAMOBAP795** [comment]
@ronaldtse I think so

**Comment by ronaldtse** [comment]
Ping @opoudjis , can we have a release soon? Thanks!

**Comment by opoudjis** [comment]
I refer you to my answer elsewhere on that.

**Comment by CAMOBAP795** [comment]
@ronaldtse I think this can be closed

**Comment by ronaldtse** [comment]
Thanks for reminding!
