### ISSUE TITLE
there should be a mn-samples-ietf

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ietf#41]
There are a bunch of sample XML documents in metanorma-ietf that can profitably be moved to mn-samples-ietf

**Comment by ronaldtse** [comment]
@opoudjis what do you need me to do?

**Comment by opoudjis** [comment]
Create the repo, and I'll dump the sample files across from metanorma-ietf

**Comment by ronaldtse** [comment]
@opoudjis I'm sure you have access to create the repo, but sure.

**Comment by ronaldtse** [comment]
@opoudjis done.

**Comment by opoudjis** [comment]
@ronaldtse Obvi not just create the repo, but set up all those GitHub Actions things that the other samples directories have.

**Comment by ronaldtse** [comment]
@opoudjis you can just copy/paste the `.github/` directory over from any of those :wink:

**Comment by opoudjis** [comment]
OK

**Comment by opoudjis** [comment]
This will contain RFC 8651. Not clear to me whether it should contain more than that.

**Comment by ronaldtse** [comment]
We should include the April fools documents here too, and also the asciirfc document.

**Comment by opoudjis** [comment]
Included April Fools doc, Antioch sample doc.
