### ISSUE TITLE
Reenable draft-iab-html-rfc-bis external refs

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ietf#5]
[&W3C.REC-CSS2-20110607;](https://xml2rfc.tools.ietf.org/public/rfc/bibxml4/reference.W3C.REC-CSS2-20110607.xml) and [&W3C.REC-html5-20141028;](https://xml2rfc.tools.ietf.org/public/rfc/bibxml4/reference.W3C.REC-html5-20141028.xml) have encoding issues in their online documentation; need to get these emended by IETF. Once they have done so, will reenable them in the rspec of draft-iab-html-rfc-bis.

This issue was encountered in #85 .

**Comment by opoudjis** [comment]
Unassinging myself. If this ever gets actioned, let me know.

**Comment by ronaldtse** [comment]
Closing since IETF is using our new BibXML service.
