### ISSUE TITLE
Gem in Windows is installing wrong version of bundler and failing in Github Actions

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ietf#50]
https://github.com/metanorma/metanorma-ietf/runs/356194985

In Mac and Ubuntu, it is correctly installing bundler 2.0.2. In Windows it is installing 2.1.1, and failing; even though the gemspec explicitly requires `spec.add_development_dependency "bundler", "~> 2.0.1"`

This applies to the "new" branch, which we're about to go live with next week. The other Metanorma gems have the same bundler setup, and don't do that with their Windows builds.

**Comment by ronaldtse** [comment]
@opoudjis this gem should not have bundler as a dependency.

**Comment by opoudjis** [comment]
All the other ones do, and they don't have this issue...

**Comment by CAMOBAP795** [comment]
Yep I will fix it for other repos too

**Comment by CAMOBAP795** [comment]
https://github.com/metanorma/metanorma-build-scripts/commit/d9e1e471d32b6e27cda520d3654b456b866d65ee

I will try to update all repos this weekends

**Comment by opoudjis** [comment]
I'm doing releases now, so can't wait for this, but it will need to work for next release.

**Comment by opoudjis** [comment]
Resolved by removing Bundler dependencies.
