### ISSUE TITLE
Github Actions Windows build cannot find `xml2rfc` executable

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ietf#53]
See https://github.com/metanorma/metanorma-ietf/commit/82dbfa663fa6c350ec119d1ba53f2a04454444ff/checks?check_suite_id=383890170 :

````
[metanorma-ietf] Error: unable to generate html, the command `xml2rfc` is not found in path.
````

**Comment by CAMOBAP795** [comment]
Fixed https://github.com/metanorma/metanorma-build-scripts/commit/c6ca95ab6cc8b803906293eb023393dcb41c1736 will be updated soon

**Comment by opoudjis** [comment]
Have just updated. Thank you.
