### ISSUE TITLE
Generate single rfc.xml suffix under metanorma

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ietf#56]
Metanorma is generating .rfc.rfc.xml

**Comment by ronaldtse** [comment]
Still broken as of now...

**Comment by ronaldtse** [comment]
[metanorma] Error: rfc.xml format is not supported for this standard.

**Comment by ronaldtse** [comment]
The output file path is correct, however, this line doesn't work:
```
:mn-output-extensions: rfc.xml,xml,txt,html,nits
```

The fix in 23f849c is really a hack -- it shouldn't be like this.

**Comment by opoudjis** [comment]
The line 

> :mn-output-extensions: rfc.xml,xml,txt,html,nits

is nonsense, since the extension is rfc, not rfc.xml, and that's fine.

If I am to not use the fix I have done, then I will be forced to reengineer isodoc to respect the filename it is passed in, when the code *is already working*. Words cannot describe how low a priority this nicety is.

**Comment by ronaldtse** [comment]
> I will be forced to reengineer isodoc to respect the filename it is passed in

In fact, isodoc should not care about the filename. It should only generate the output and have something else handle the file saving part.

**Comment by opoudjis** [comment]
This reengineering is now taking place in https://github.com/metanorma/metanorma-standoc/issues/285 . The format name remains rfc.

**Comment by ronaldtse** [comment]
> The format name remains rfc.

Great, thanks.

**Comment by ronaldtse** [comment]
As long as it is documented on metanorma.com!!
