### ISSUE TITLE
Make option so that Metanorma controls bibliography, not xml2rfc

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#65]
In IETF RFC 7991 it is said that authors should use `ENTITIY` `xinclude` (or similar) to include RFC references.

However, some authors have stated that is undesirable because the document cannot be compiled without an internet connection, even when the XML references are manually inserted (via relaton cache, AsciiBib or manual relaton XML).

An option is necessary for MN IETF to "embed full references" so that xml2rfc does not fetch references.

This is one of the requests from #63 .

**Comment by opoudjis** [comment]
Added option `:use-xinclude:` to trigger xinclude behaviour.
