### ISSUE TITLE
Feature request: pass-through to XML RFC

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#69]
This is a suggestion from @petithug (sorry for the late posting!):

The issue is that pass-through at the AsciiRFC level requires to use metanorma XML model, but it would be useful to be able to pass-through xml2rfc, for example to use some of the xml2rfc features that have no equivalent in AsciiRFC, at least until they are implemented.  Let's use `<artset>` as an example.  One cannot do that:

```xml
<artset>
 <artwork>
...
 </artwork>
</artset>
```

because metanorma XML (and AsciiRFC) does not know anything about `<artset>` yet.  So my suggestion is to add a new type of node in metanorma XML that can carry any value, something like this:

```xml
<pass-through>
<artset>
  <artwork>
    ...
  </artwork>
 </artset>
</pass-through>
```

Then the back-end for IETF (and probably others) can be modified to simply add the content of the `<pass-through>` element inside the xml2rfc document.

**Comment by opoudjis** [comment]
Passthrough exists now in Metanorma, although it's not broadcast, and downstream processing won't do anything special with it; it would need to be wrapped in something like a tag, yes.

Pass through is obviously utterly meaningless if the target is not exclusively another XML variant: the only current flavour it has any relevance at all is IETF. In other flavours, it's non-Metanorma XML that at least one of HTML, XSL:FO, and MHT is going to have to spit out, since there is no markup shared by the three.

I can implement passthrough in Metanorma-IETF, but frankly, I don't want to: it compromises the XML we have. The notion of image surrogates is awkward for the current Metanorma information model, but passthroughs would be a lot more awkward.

**Comment by petithug** [comment]
That's fine, I'll implement it in my fork.

Thanks.

**Comment by opoudjis** [comment]
We do want to support as much of RFC XML 3 as possible, to avoid the need for passthrough in the first place; I've listed the unsupported elements in https://www.metanorma.com/author/ietf/ref/unsupported-rfc-elements/

@petithug, Could you let us know which of those are a priority for you?

**Comment by petithug** [comment]
Will do.  I am currently focusing on the bibliography part.

**Comment by ronaldtse** [comment]
> That's fine, I'll implement it in my fork.

@petithug we will have this implemented.

1. In order to implement this we will need to make a `<passthrough>` block (i.e. so that XML stuff inside the block won't break the document.

2. The passthrough block is format targeted, i.e. it will only be rendered in the desired output format, e.g.

```adoc
[passthrough,format=xmlrfc]
....
<artset>
  <artwork>
   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
   \\\\\\\\\\\\\\\\\\\\\^^^^^^^^^^^^^^^^^^^^^^\\\\\\\\\\\\\\\\\
   \\\\\\\\\\\\\\\\\\\<<#MWSHARPMWMWMWTEETHWMWWM>>>\\\\\\\\\\\\
   \\\\\\\\\\\\\\\<<<#WMMWMWDEEPMDARKWCAVEMWWMMWM##>>>>\\\\\\\\
   \\\\\\\\\\\\\<<#WMWMWMWMWWM/^MWMWMWMWMWMW^WMWMWMMW#>>>\\\\\\
   \\\\\\\\\\\\<<#WMWMBEASTMW// \MWABBITWMW/ \MWMWMWMW##\\\\\\\
   \\\\\\\\\\##MWMWMMWMWMWMWM\\  \MWMWMWMW/  /MWMWMWMWM##\\\\\\
   \\\\\\\\##WMWMWMWMMWMWMWMWM\\  \MWMWMW/  /MWMWMWMMWMWMWM##\\
   \\\\\\\##MWMMRAVENOUSMWMWMWM\\  \====/  /MWMRABBITMWMWMWMW##
   \\\\\\##MWMWMWMWMMWMWMWMWMW[[            ]WMWMWMMWMWMWMWMWMW
   \\\\\##MWMWMWMWCARNIVOROUSW[[   3    3   ]MWMWTOOMDARKWMWMMW
   \\\\##MWMWDARKMWMWMWMWMWMWM//\     o    /MWMWMWMMWMWMWMMWMWM
   \\##MWMWMMKILLERABBITWMWMM//| \___vv___/ \WMPITCHWBLACKWMWMW
   \##MWMWMWMMWMWMWMWMWMMWMW// |   \-^^-/   |MWMWMWMMWMWMWMWMWM
   MWMWMWMMWMWVERYMDARKWMMW//  |            |MWMCAERBANNOGWMWMW
   MWMWMWMMWMWMWMWMWMWMWMM{{  /             /MWMWMMWMWMWMWMWMWM
   MULTRADARKWMWMHELPMWMWMW\\ \  |      |  |MWMCANMMWMWMWMMWMWW
   MWMWMWMWMMWMWMWMWMMWMWMWM\\ | |_     |  |_WMWMMYOUMWMMWWMWMW
   MWMMWMWMWMWMBLACKWMWMWMWWM\_|__-\-----\__-\MWMWMWMREADMWMWWM
   MWMWMWMMWMWMWMWMMWMWMWWMWMWMWMMWMWMWMWMWMWMWMWMWMWMWMMTHISWW
   MWVERYMMSCARYMWMWWMWMMWMWMWMWMWMWMWMWMWMWMWMWWMWMMWMWIWM'.',
   MWMWMMWMW======MWMMCANTWSEEMAMTHINGMMWMWMWMWMWMWMBETMMW` . `
   MWMWMWM// SKULL \MWMWMWMMWSCREAMMMWMWMWMMWMNOTMWMWMWW  ` . \
   MWMWMW|| |X||X| |MWMWCALLMMEWMMWMWMMWMWMWMWWM - ` ~ . , '
   MWMWMW||___ O __|MWMWMWMMWMWMWMWMMW'   ___________//   -_^_-
   MWMWMW \\||_|_||MWMW      '   . .     <_|_|_||_|__|     \O/
   MW   \\/\||v v||  -\\-------___     .   .,         \     |
       \\|  \_CHIN/  ==-(|CARROT/)\>     \\/||//         v\/||/
          )          /--------^-^            ,.            \|//
    #  \(/ .\\|x//                              " ' '
     . ,                \\||//        \||\\\//   \\
  </artwork>
</artset>
....
```

Any comments on this direction?

**Comment by opoudjis** [comment]
I've implemented this, pending feedback; the format is:

````
[format=html,rfc]
++++
<artset>
<artwork>
X
</artwork>
</artset>
++++
````

I'm using the native passthrough notation of AsciiDoc. Format names the output formats which will use the block; if left out, it will output the passthrough content to all output formats (which for IETF is fine.)

**Comment by petithug** [comment]
I think that will work just fine, thanks.

**Comment by ronaldtse** [comment]
There is a caveat in the passthrough:
* The passthrough-ed data automatically becomes XML-valid, because the final RFC XML output is built using an XML engine. The XML engine will close any missing tags if any.

This means that the following usage is not possible now:

```adoc
[format=html,rfc]
++++
<artset>
<artwork>
++++

.Rabbits fighting for a carrot
|===
| RABBIT | CARROT | RABBIT
|===

[format=html,rfc]
++++
</artwork>
</artset>
++++
```

It's certainly feasible to open that possibility but not sure if that's useful, it also involves more resourcing.

There is also a use case where the passthrough involves "including" external XML files (instead of inline XML), which doesn't seem to be supported yet?

**Comment by petithug** [comment]
I think that the content of the passthrough block should be copied without interpreting it or trying to repair it, directly in the xmlrfc document generated.  If it is incorrect, it is the responsibility of the user to fix it.

The modification is not in fact a new feature, it is bringing back a feature that was existing all along (injecting raw text in the output) but that disappeared when an intermediate representation (metanorma xml) was inserted between Asciidoc and the rendered document (which is xml2rfc in the metanorma-ietf case). I do not think that the choice of the next rendering layer (text, html, pdf) is that important, as ifdef can be used to choose different passthrough raw text.

Basically what I am saying is that the new feature should permit to do what a passthrough block did before, no more, no less.  We just need a flag to tell if the raw text is injected in metanorma xml (as currently done) or in the text generated at the next layer -- that's it.

Finally note that this is not just about generating code for features that are not implemented yet in metanorma.ietf (like artset).  Passthrough is an important feature to be able to experiment on eventual new features before implementing them.  Maybe I want to design a new AsciiDoc block (and its processor), but first I want to get a good idea of how it will be rendered, and passthough is an invaluable tool to quickly experiment on that. That is still my main use case.

**Comment by ronaldtse** [comment]
I believe we can implement a real passthrough this way, we just need to run some experiments to see whether we can bypass nokogiri.

**Comment by ronaldtse** [comment]
I think the proper way to implement non-intrusive passthrough is by wrapping `<passthrough>` tags in MN XML, and then as a last step during rendering, strip the tags away e.g. `gsub`.

This will restore previous behavior, and also allow other formats to accept this kind of passthrough text :

```adoc
[format=html,rfc]
++++
<artset>
<artwork>
++++

.Rabbits fighting for a carrot
|===
| RABBIT | CARROT | RABBIT
|===

[format=html,rfc]
++++
</artwork>
</artset>
++++
```

**Comment by opoudjis** [comment]
Implementing tonight. If the result of expanding out passthroughs is going to be malformed XML, I'll be aborting execution.

**Comment by ronaldtse** [comment]
> Implementing tonight. If the result of expanding out passthroughs is going to be malformed XML, I'll be aborting execution.

I don’t think we need any error checking here, if the user breaks the result with passthrough, that should be considered intended.

**Comment by opoudjis** [comment]
The problem is that the postprocessing is going to keep going (down to html2doc for Word documents). Either the broken markup will be silently emended in Nokogiri (although I am now parsing strictly), or the markup will be broken *with no diagnostic statement to help the user*. That's too much.

**Comment by ronaldtse** [comment]
Thanks @opoudjis ! @petithug can you check whether this satisfies your requirements? Thanks!

**Comment by opoudjis** [comment]
Note that this won't appear in the released gem until next release, currently scheduled for next Friday.

**Comment by petithug** [comment]
Going back to this now...
It seems that the passthrough block that I used previously to pass bibitem are no longer processed but passed to xml2rfc.  Apparently what I pass there is wrapped in a <passthrough> element which then pass to the next stage,

That's not what was expected.  The <passthrough> element should be passed in the passthrough block, so at the adoc level, one can choose between isodoc XML (no <passthrough> element) or xml2rfc (inside a <passthrough> element).

**Comment by ronaldtse** [comment]
@petithug is the purpose here is to insert `<bibitem>` into Metanorma XML (isodoc) to enable local insertion of bibliographic data?

This syntax is already supported if the purpose is to insert passthrough to the end formats:

```
[format=html,rfc]
++++
<artset>
<artwork>
++++

.Rabbits fighting for a carrot
|===
| RABBIT | CARROT | RABBIT
|===

[format=html,rfc]
++++
</artwork>
</artset>
++++
```

If the goal is what I phrased above, can we enable that with allowing interpretation of local bibdata?

**Comment by petithug** [comment]
The high level concept is two have two different escape hatches, for when a feature is too new to be yet implemented in metanorma (or simply to experiment):

- The first one permits to insert any XML fragment (valid or not) at any place in the Standoc XML tree.  That's how I could insert <bibitem> until recently, but it should not be limited to that.

- The second one permits to insert any XML fragment (valid or not) at any place in the XML2RFC XML tree.  That's how I could insert <reference> until metanorma-ietf 2.0, but it should not be limited to that.

One way to do that was to restore the first escape hatch above and to implement the second as a <passthough> element in Standoc XML , but I am fine with any other way to implement that feature.

**Comment by opoudjis** [comment]
Passthrough of Metanorma XML will be realised as:

````
[format=metanorma]
++++
<artset>
<artwork>
X
</artwork>
</artset>
++++
````

or as pass block with no format indication.
