### ISSUE TITLE
`intended-series` not working as intended

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#75]
On this page: https://www.metanorma.com/author/ietf/ref/document-attributes/

<img width="803" alt="Screen Shot 2020-06-10 at 1 20 57 AM" src="https://user-images.githubusercontent.com/11865/84179499-a3fa0f80-aab8-11ea-92b3-e40cdfe0999e.png">

I have tried the values:
`standard`
`full-standard`

But the resulting document shows this error:
```
Error: Invalid attribute category for element rfc, at /rfc
Error: Invalid document before running preptool.
Unable to complete processing draft...
```

Seems that xml2rfc does not treat these values as valid. Can we double check the latest RFC v3 spec?

**Comment by opoudjis** [comment]
xml2rfc/Levkowetz have chosen to conflate the category and seriesInfo items, but have not redefined category to use the same vocabulary as seriesInfo: category still uses v2 values. Fixing by mapping seriesInfo values to v2 values.
