### ISSUE TITLE
Confusion and brokenness of attributes: docname, name, docnumber

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#82]
Documentation says: 
https://www.metanorma.com/author/ietf/ref/document-attributes/

<img width="778" alt="image" src="https://user-images.githubusercontent.com/11865/85323750-27752100-b4fb-11ea-9420-38c5b96ef349.png">

"rfc@docName will be set to the :name: attribute"

This is not true. `docName` is actually set to `:docnumber:`. Both `:docname:` and `:name:` don't work.

Without setting `:docnumber:`, the `rfc@docName` will not be set.

For example, this code:
```adoc
:doctype: internet-draft
:docname: acvp-iana
:name: draft-ietf-acvp-iana-1.0
:status: informational
:submission-type: independent
:intended-series: info
:abbrev: ACVP IANA
```

Gives this error:
```
draft-gold-acvp-iana.rfc.xml(8): Warning: Expected a 'docName' attribute in the <rfc/> element, but found none.
draft-gold-acvp-iana.rfc.xml(8): Error: Expected a valid category for submissionType='independent', one of exp,historic,info, but found 'std'
```

Moreover, if `:submission-type: independent` is set, the `category` should NOT be set to `std` (because it is invalid), it should fail schema validation.

This works (compared to the previous example):
```adoc
:doctype: internet-draft
:docnumber: draft-ietf-acvp-iana-1.0
:status: informational
:submission-type: independent
:intended-series: informational
```

The documentation on metanorma.com should be updated to provide examples on how this works. The document example `antioch/document.adoc` on mn-samples-ietf is also wrong:

```
:submission-type: independent
:intended-series: info    =>  :intended-series: informational
```

Either we accept the acronym (the original RFC XML value), or we don't.

_This was discovered at https://github.com/celic/acvp-metanorma/pull/6_

**Comment by opoudjis** [comment]
The issue with intended-series has already been addressed in https://github.com/metanorma/metanorma-ietf/issues/75, and results from xml2rfc adhoccery (restoring a v2 attribute that is a distinct vocabulary from v3).

**Comment by opoudjis** [comment]
The intent is indeed to use v3, not v2 attributes for intended-series: informational not info. But I'm going to allow both values in Metanorma XML, outputting the right value in RFC XML.
