### ISSUE TITLE
Broken `:initials:` attribute

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#83]
The initials are not filled in MN XML, and also not passed to RFC XML.

```adoc
:initial: A.
:surname: Pendragon
```

See:
<img width="451" alt="Screen Shot 2020-06-23 at 2 51 37 AM" src="https://user-images.githubusercontent.com/11865/85324464-77a0b300-b4fc-11ea-8f8d-7ea685e85af1.png">

**Comment by opoudjis** [comment]
Error, it should be `:initials:`
