### ISSUE TITLE
Run schema validation on generated XMLRFC v3 document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#89]
https://svn.tools.ietf.org/svn/tools/xml2rfc/trunk/cli/xml2rfc/data/v3.rnc

Given that we often seen rejected output of XMLRFC v3, it would be wise to first validate ourselves before passing the output to xml2rfc.

**Comment by opoudjis** [comment]
I'll do this, but this won't substitute for https://github.com/metanorma/metanorma-ietf/issues/93 for implementing hardcoded validation rules of xm2lrfc, which are in fact unrelated to the schema.

**Comment by opoudjis** [comment]
Validating, not aborting if errors found.
