### ISSUE TITLE
Abstracts used to be `[abstract]`, but now only `.Abstract` works -- why?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#94]
This used to work:

```adoc
[abstract]
This specification introduces a new iCalendar component which allows
for consensus scheduling, that is, voting on a number of alternative
meeting or task alternatives.
```

Now only this works:

```adoc
.Abstract

This specification introduces a new iCalendar component which allows
for consensus scheduling, that is, voting on a number of alternative
meeting or task alternatives.
```

Why?

**Comment by opoudjis** [comment]
I don't know whether this is an update from asciidoctor 1.5.8 to asciidoctor 2.1.0, but 

````
[abstract]
This specification introduces a new iCalendar component which allows
for consensus scheduling, that is, voting on a number of alternative
meeting or task alternatives.
````

is nonsense in Asciidoctor markup: style attributes in Asciidoctor only apply to titles. Without a title, asciidoctor is detecting that there is a preamble (text before the first section), but is simply ignoring its content: the `node.content` is in fact an empty string, and `node.lines` is an empty list. This is Asciidoctor parsing, and thus there is nothing for me to do here. (And I very strongly suspect it never worked.)
