### ISSUE TITLE
Date incomplete in generated xml2rfc 

### ISSUE THREAD

**Issue by petithug** [metanorma/metanorma-ietf#98]
a `<reference>` for an RFC should contain a date element with Month and Year.  A `<reference>` for an I-D should contain a date element with Day, Month and Year.
Regardless of the date entered in AsciiBib, metanorma-ietf  should be able to figure out what to put in the xm2rfc element, but it seems that the date is apparently truncated to just Year in metanorma-standoc, and so the problem cannot be fixed entirely in metanorma-ietf.

**Comment by opoudjis** [comment]
Issue is in our bibliographic processing: the AsciiBib is parsing the dates at the desired granularity, but the XML generated in relaton/relaton-bib is serialising them at year granularity. Raised ticket for my colleague Andrej to address.

**Comment by ronaldtse** [comment]
FYI @petithug the dependent issue relaton/relaton-bib#34 should be resolved soon, we should be able to resume this shortly.

**Comment by opoudjis** [comment]
This issue is resolved and confirmed working in metanorma-ietf unit testing, it will be available next release of metanorma (expected November 23.)
